### ISSUE TITLE
Add my project, please: Tally

### ISSUE THREAD

**Issue by mhluongo** [ethers-io/website#12]
Project details!

* GitHub [repo](https://github.com/tallycash/extension), GPLv3
* Email or Twitter: **team@tally.cash** + **[@tallycash](https://twitter.com/tallycash)**

![7QR2OL79_400x400](https://user-images.githubusercontent.com/427505/147603057-4ab64668-3a79-41d2-ae95-7139b10255f3.jpg)

**Comment by ricmoo** [comment]
Added, thanks! :)
