### ISSUE TITLE
Add my project, please: Unlock

### ISSUE THREAD

**Issue by julien51** [ethers-io/website#5]
Thanks for using ethers and we look forward to including a link to your project on ethers.

Please include the following details:

- Link to GitHub repository: https://github.com/unlock-protocol/unlock/
- A 256x256 px image (JPG or PNG) for a logo to include: https://github.com/unlock-protocol/unlock/blob/master/design/brand/PNG/Unlock-LogoMark-Circle.png
- A public e-mail address or Twitter account with DMs enabled julien@unlock-protocol.com

Thanks @ricmoo !

**Comment by ricmoo** [comment]
Looks good! I’ll get to this shortly. :)

**Comment by ricmoo** [comment]
Added, uploaded and the edge caches flushed. You should see it up there now. :)

Thanks! :)
