### ISSUE TITLE
Add my project, please: AlphaWallet

### ISSUE THREAD

**Issue by sharonsylu** [ethers-io/website#6]
Please include the following details:

- Alphawallet, 100% open self custodial wallet 
- MIT licence, free for open and commercial licence, forks welcome.
- Github:  https://github.com/AlphaWallet/
- Email: info@alphawallet.com
- Twitter (DMs open): @alphawallet

![Alphawallet_400x400](https://user-images.githubusercontent.com/15342675/128205794-75c7438d-9853-4061-986b-1f2f8f894271.jpeg)

Big Kudos, the engineering team love ethers.js and we wholeheartedly recommend to our engineers and devs. Thank you for being part of the contributing ethereum ecosystem!

**Comment by ricmoo** [comment]
I've added this to my local version and published it, but mixed up the branches a bit. I will close this issue once the changes are pushed to the repo. :)

**Comment by sharonsylu** [comment]
Thanks Richard 👍  Let us know if there is anything we can do likewise to help or give feedback on your work :)

**Comment by ricmoo** [comment]
The repo has been pushed and looks like its all good. :)

Thanks!
