### ISSUE TITLE
Add my project, please: ether-swr

### ISSUE THREAD

**Issue by aboutlo** [ethers-io/website#9]
Hey,

I would like to have `ether-swr` added

- GitHub repository: https://github.com/aboutlo/ether-swr
- A 256x256 px image (JPG or PNG): ![etherSWR_logo_square](https://user-images.githubusercontent.com/1236268/136550171-3134da60-fe09-429d-9618-63e7b8cc37d8.png)
- twitter account: @aboutlo

tks!

**Comment by ricmoo** [comment]
Added, thanks! :)
